services:
  - type: web
    name: airtel-backend
    # Spécifie l'environnement d'exécution
    env: node
    # Spécifie le plan (gratuit)
    plan: free
    # Indique à Render où se trouve le code du backend
    rootDir: backend
    # Commande pour installer les dépendances
    buildCommand: "npm install"
    # Commande pour démarrer le serveur
    startCommand: "node index.js"
    envVars:
      # Indique que la valeur de la variable d'environnement GOOGLE_APPLICATION_CREDENTIALS_JSON
      # doit être récupérée depuis le secret store de Render, à partir d'un secret nommé 'ServiceAccountJSON'.
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        fromSecret: ServiceAccountJSON # Le nom du secret que vous allez créer dans le dashboard Render